GET http://localhost:3000/cocktails

###

# Get valid cocktail
GET http://localhost:3000/cocktails/1

###
# Get invalid cocktail
GET http://localhost:3000/cocktails/1000

###
POST http://localhost:3000/cocktails
content-type: application/json

{
    "name": "Fruit Tingle",
    "base": "Vodka",
    "instructions": "Add the vodka, blue curacao & lemonade then give it a light stir. Pour a small dash of raspberry cordial on top. Garnish with a pineapple wedge or maraschino cherry"
}

###
PUT http://localhost:3000/cocktails/4
content-type: application/json

{
    "name": "Fruity Tingle",
    "base": "Vodka",
    "instructions": "Add the vodka, blue curacao & lemonade then give it a light stir. Pour a small dash of raspberry cordial on top. Garnish with a pineapple wedge or maraschino cherry"
}